@startuml Robodogクラス図
skinparam classAttributeIconSize 0
hide circle

class RoboDog {
 -myName: String
 -myTime: int
 -goodMorning: String
 -goodAfternoon: String
 -gootNight: String
 -firstValue: int
 -secondValue: int
 -result: int

 +getMyName(): String
 +setMyName(): void
 +setMyTime(): void
 +getMyGreeting(): String
 +setTwoValues(): void
 +setResult(): void
 +getResult(): int
}

@enduml
